module.exports = {
  api: {
    url: '/api',
    endpoints: {
      authenticateUser: '/users/authenticate',
      createUser: '/users/create',
      getPerson: '/users/person', 
      userRegister: '/users/register',
      updateUser: '/users/update',
      getSelectData: '/users/dataSelect',
      userData: '/users/userData',
      getEvents: '/users/getEvents',
      getPublications: '/users/getPublications',
      uploadPost: '/users/uploadPost',
      getInscriptions: '/users/getInscriptions',
      getPersonEvents: '/users/getPersonEvents',
      getEventInscripted: '/users/getEventInscripted',
      deletePost: '/users/deletePost',
      getSelectDataNewEvent: '/users/getSelectDataNewEvent',
      createEvent: '/users/createEvent',
      getEvent: '/users/getEvent',
      getCategories: '/users/getCategories',
      getEventCategories: '/users/getEventCategories',
      getFaq: '/users/getFaq',
      uploadQuestion: '/users/uploadQuestion',
      getPublicationsByUser: '/users/getPublicationsByUser',
      getPublicationsNoAdmin: '/users/getPublicationsNoAdmin',
      getPublicationsAdmin: '/users/getPublicationsAdmin',
    },
  },
};
